### ISSUE TITLE
Request for revising the link of README.

### ISSUE THREAD

**Issue by YeongHyeon** [izmailovpavel/flowgmm#1]
Hello, 
I confirm that some links in README of this repository don't work.

The example link that provided via README is follows.
Text: The experiments on synthetic data are implemented in 'this ipython notebook'.
Original Link: https://github.com/izmailovpavel/flow_ssl/blob/public/experiments/synthetic_data/synthetic.ipynb
Link for revising: https://github.com/izmailovpavel/flowgmm/blob/public/experiments/synthetic_data/synthetic.ipynb

Thank you for reading this issue!

**Comment by izmailovpavel** [comment]
Hi @YeongHyeon, thanks for the catch! I think I fixed all the links now in 9cf5a1fad890ecd1df55c059b9d59c83ba038e75.
