### ISSUE TITLE
about gmm weight

### ISSUE THREAD

**Issue by akidway** [izmailovpavel/flowgmm#12]
Hi,

Thank you for your great work.

In the code [here](https://github.com/izmailovpavel/flowgmm/blob/071285be739defd548ed0c90eec9e56e1112b773/flow_ssl/distributions.py#L18), it appears that you compute gmm weights directly using a gradient-based method, which differs from the traditional EM method. Could you confirm if my understanding is correct?

Thank you!

**Comment by izmailovpavel** [comment]
Hey @akidway, thank you for checking out the code! I believe we explored both EM-style updates and direct optimization with SGD, and found that SGD works similarly or better.
