### ISSUE TITLE
"MakeTabularTrainer() got an unexpected keyword argument" when training "train_semisup_flowgmm_tabular.py"

### ISSUE THREAD

**Issue by JasonZhang06** [izmailovpavel/flowgmm#3]
When training the FlowGMM using "train_semisup_flowgmm_tabular.py", in the line 87: "thestudy.run(3,ordered=False)" , I get a typeError: makeTabularTrainer() got an unexpected keyword argument 'num_epochs'.
I would appreciate it very much if you can help me deal with this error!  @izmailovpavel

**Comment by mfinzi** [comment]
Hi Jason. It looks like one of our dependencies changed. Sorry for the disorganized code! We made some changes to make it easier to run the models on the tabular data, which for MINIBOONE and HEPMASS download when you run the script. The details are in the new README.
Here is an example to run on MINIBOONE:
```
python3 experiments/train_flows/flowgmm_tabular_new.py --trainer_config "{'unlab_weight':3.}"\
 --net_config "{'k':256,'coupling_layers':10,'nperlayer':1}" --network RealNVPTabularWPrior \
 --trainer SemiFlow --num_epochs 300 --dataset MINIBOONE --lr 3e-4
```
