### ISSUE TITLE
Keyword error while training for CIFAR10

### ISSUE THREAD

**Issue by yashasvi97** [izmailovpavel/flowgmm#6]
Hi,
Thanks for the code. I am trying to run the experiments for CIFAR10, I downloaded the dataset via setup script. I installed the dependencies. But when I run the code with the example command given I am getting the following error.

Command I ran:
<code>
python experiments/train_flows/train_semisup_cons.py --dataset=CIFAR10 --data_path=data/images/cifar/cifar10/by-image/ --label_path=data/labels/cifar10/4000_balanced_labels/10.txt --logdir=logdir --ckptdir=ckptdir --save_freq=500 --num_epochs=1501 --label_weight=3 --consistency_weight=1. --consistency_rampup=100 --lr=1e-4 --eval_freq=50
</code>

Output:
<code>
2020-10-23 15:47:34.626934: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64
2020-10-23 15:47:34.626962: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

**Traceback (most recent call last):
  File "experiments/train_flows/train_semisup_cons.py", line 259, in <module>
    return_all_labels=args.acc_train_all_labels,)**  
**File "/MYSYS_BASE_PATH/flowgmm/flow_ssl/data/ssl_data_utils.py", line 39, in make_ssl_data_loaders
    args, kwargs)**  
**TypeError: make_ssl_cifar_data_loaders() got an unexpected keyword argument 'return_all_labels'**  
</code>

It would be great if you could help me out with this issue.
Thanks in advance!
Regards,
Yashasvi

**Comment by yashasvi97** [comment]
Adding *args, **kwargs in the definition worked. Further when you run the code, there is another issue with init_zeros argument in resnet.py. I guess this new version of code doesn't have init_zeros keyword in resnet definition. You could update that part in the code. 
Otherwise thanks again for the code.
Cheers, 
Yashasvi

**Comment by izmailovpavel** [comment]
Hey @yashasvi97 thanks for posting, we will look into this
